### ISSUE TITLE
无法使用astool

### ISSUE THREAD

**Issue by niubo-xingshen** [BioGavin/astool#1]
谢谢作者的代码帮助，请问以下怎么安装astool

**Comment by BioGavin** [comment]
您好，我并没有提供pip或conda安装的方式。您可以将astool包文件放入例如conda环境中`~/miniconda3/envs/astool/lib/python3.8/site-packages`这样的路径下，这样您在使用script中的脚本时就可顺利调用astool包中的内容。

**Comment by niubo-xingshen** [comment]
非常感谢！
