### ISSUE TITLE
Compatibility with antismash v7.0

### ISSUE THREAD

**Issue by ellyyuyang** [BioGavin/astool#2]
Dear authors,

Thanks for supplying these scripts!

I wanted to ask if these scripts are compatible with antismash v7.0?

The reason I am asking is that, when I run `ex_knownclusterblast_from_json.py`  with json outputs from antismash v7.0, I get empty outputs of `knownclusterblast_hits_detail_output.tsv` and `knownclusterblast_hits_number_output.tsv` without any warning messages. So I am unsure what is not working. 

Thanks for helping!

Best,
Yu

**Comment by BioGavin** [comment]
You need to check that the `--cb-knownclusters` flag is turned on when running antismash.

**Comment by ellyyuyang** [comment]
Thanks @BioGavin , it worked now!

**Comment by ellyyuyang** [comment]
Thanks @BioGavin  , it worked now!
