### ISSUE TITLE
Explaination of headings in the outputs of ex_knownclusterblast_from_json.py

### ISSUE THREAD

**Issue by ellyyuyang** [BioGavin/astool#3]
Dear authors,

Thanks for the tool and it worked well for me. 

I would like to ask about what the headings in the output of **`ex_knownclusterblast_from_json.py`** mean? 

So for output **`knownclusterblast_hits_detail_output.tsv`**, I have the following headings that I am unsure of the meaning for the table:
     

- **blast_score** : since there are multiple genes that are present in a given BGC, how is the blast score obtained?

- **MIBiG_similarity_precise_proportion** : what does simiarity mean here? aa similarity? or the "completeness" of a given BGC (as in the proportion of genes in a BGC that is detected)

- **MIBiG_similarity_rough_proportion** : this seems intuitive, looks like just the rounded value of "MIBiG_similarity_precise_proportion"

As for the headings of the output **`knownclusterblast_hits_number_output.tsv`**:

- **total_hits** : seems like this column represents the number of BGCs identified for a given genome? this seems to come from unfilter BGC detection results (unfiltered by the "completeness" of BGCs)?

Based on your experience, what are your comments on applying a BGC completeness cutoff (like 80%, 50%, 100%, etc.)?

Hope I am making sense of myself!

Thanks,
Yu

**Comment by BioGavin** [comment]
Hey, Yu.

I think you might want to read up on [this link](https://docs.antismash.secondarymetabolites.org/modules/clusterblast/#:~:text=KnownClusterBlast%3A%20shows%20clusters%20from%20MIBiG,related%20to%20the%20current%20region) first.

To be honest, I haven't specifically looked into how blast scores are obtained, but I'm guessing it would be the sum of the blast scores for each corresponding gene, with higher scores indicating more similarity to the reference BGC.

**total_hits**: this means the number of reference known BGCs that were matched with the query BGC.

Finally, I don't understand what the BGC completeness cutoff you mentioned is used for?
